
CHANNEL_TYPE = "channel_type"
TYPE = "type"
RAW_CONTENT = "raw_content"
NICKNAME = "nickname"
K_MARKDOWN = "kmarkdown"
EXTRA = "extra"
AUTHOR_ID = "author_id"
CONTENT = "content"
AUTHOR = "author"
CHANNEL_NAME = "channel_name"
TARGET_ID = "target_id"
USERNAME = "username"
IDENTIFIED_USERNAME = "identified_username"
IDENTIFY_NUM = "identify_num"
MSG_ID = "msg_id"

